### ISSUE TITLE
Insert into Impala tables from local pandas DataFrame

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#197]
Requested by user. This ought to be doable; it would be easier if there were an easy path from pandas to Parquet, but there's not right now. Will investigate

**Comment by sampathpulukurthi** [comment]
Hi Team,, 

I am using impyla to connect python and impala tables and executing bunch of queries to store the results into a python data frame.

Now, I want to push the data frame into impala and create a new table or store the file in hdfs as a csv. Can you post the solution if you have got one? I see lot of discussion above but I could not find the right code for it. I hope to hear from you soon!

**Comment by ddonetskov** [comment]
I'd like to support this suggestion. I am starting to work with Kudu (via Impala) with most of my data processing being done with pandas. I'd be happy to be able to read and write data directly to/from a pandas data frame. Thank you!

**Comment by joolius** [comment]
Any progress on this yet? I'm also querying some data from impala, and I need a way to store it back.

**Comment by koka0901** [comment]
df = spark.sql("SELECT * FROM dbname_.table_name")
df will be a spark dataframe
to write df again as a table:
df.write.insertInto('some_table')
this table needs to exist first.

**Comment by floriancastelain** [comment]
Hello. Are you planning to implement this ? Not being able to perform an insert into is very problematic.

**Comment by datapythonista** [comment]
This is already implemented: https://ibis-project.org/docs/backends/impala.html#ingesting-data-from-pandas
