### ISSUE TITLE
Ibis schema support for nested types

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#203]

**Comment by wesm** [comment]
@laserson can you let me know when you try out impyla against a table with nested types?

**Comment by laserson** [comment]
It's good to go.  All result-set schemas must be flat, so there is no way to get back nested Thrift objects.  (This is not true for Hive, but should be all good with Impala.)

**Comment by cpcloud** [comment]
Ibis has supported describing tables with nested data since #848.
