### ISSUE TITLE
Ensure ImpalaClient.drop_database with force=True drops all necessary object types

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#290]
Follow-on to #283 that not ready to address yet

- [x] views
- [x] aggregate functions
- [x] scalar functions

**Comment by megvuyyuru** [comment]
I can definitely close the loop on scalar and aggregate functions now that I rewrote the show_functions stuff.

**Comment by wesm** [comment]
reopening and moving to 0.5 milestone (need to add testing and support for dropping aggregate functions also)
