### ISSUE TITLE
Python 3 support with single codebase (no 2to3)

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#297]
I'd like to make this a stretch goal for 0.3. Now that impyla 0.10 and higher supports Python 3, we should be able to also without too much hardship.

**Comment by arahuja** [comment]
I also run into an issue with the kerberos library and py3 - is there a workaround for that?

Seems similar to the issue in requests-kerberos: https://github.com/requests/requests-kerberos/issues/52

```
Collecting kerberos==1.1.1 (from requests-kerberos->hdfs[kerberos]>=1.1.1->ibis-framework)
  Using cached kerberos-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/b1/jbv4n2f56mz8m3hxkdtc51cr0000gn/T/pip-build-66l592_d/kerberos/setup.py", line 19, in <module>
        import commands
    ImportError: No module named 'commands'
```

**Comment by wesm** [comment]
That's problematic. I haven't tried installing dependencies on Python3 yet

**Comment by eyadsibai** [comment]
Deprecated since version 2.6: The commands module has been removed in Python 3.0. Use the subprocess module instead.

**Comment by wesm** [comment]
We'd already been discussing making kerberos optional per #453, so if that helps get python3 faster, then let's do that

**Comment by eyadsibai** [comment]
well.. we wanna try your new awesome library ... :+1:

**Comment by wesm** [comment]
as context, the original blocker for python 3 (and I would have loved to start the project out with 3.4 as the target) was thrift, but now there is thriftpy (barely a year old) and impyla uses that, so we're no longer blocked. I'm ready for the switch :)

**Comment by ianozsvald** [comment]
+1 curious to have a play but I'm Python3.4+ only

**Comment by wesm** [comment]
Should have Py3 support by end of month or sooner, since support in mtth/hdfs is dropping soon https://github.com/mtth/hdfs/commits/python3

**Comment by mtth** [comment]
Version `2.0.0` of `hdfs` is indeed almost ready, with python 3 support. This release has a significant number of improvements but also a few breaking changes which might affect `ibis` (see [here](https://github.com/mtth/hdfs/blob/python3/CHANGES) for the list of changes). Please don't hesitate to reach out if you have any concerns or suggestions.

Ps - sample improvements:

+ Support for python `2.6`, `2.7`, `3.3`, `3.4`.
+ Hooks for download and upload progress (along with better parallelization of each).
+ A few new client methods (e.g. `Client.makedirs`).
+ Kerberos client robustness improvements (though installing its dependencies is a bit tedious in python 3).

**Comment by mtth** [comment]
@wesm - FYI, I'm planning on releasing `2.0` sometime next week.

(I see that `hdfs` only has a lower bound in `ibis`' `requirements.txt` so you might want to pin it if some of the breaking changes affect you.)

**Comment by wesm** [comment]
Thanks, I will do. Will support 2.0 and Python 3 in the next Ibis release

**Comment by wesm** [comment]
Python 3 support (single codebase) is now in master
