### ISSUE TITLE
Improve docstrings for hdfs_connect and impala_connect

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#444]
@laserson can you take a crack at these?

**Comment by laserson** [comment]
whoops, totally missed this issue

**Comment by laserson** [comment]
The interface for connecting to Impala will change a bit when cloudera/impyla#97 gets merged in, which will probably only happen next week.

**Comment by wesm** [comment]
sounds good, thanks

**Comment by laserson** [comment]
Are we ready to cut a new release of impyla?  I'd like to get that interface change released so we can have it reflect here.

**Comment by wesm** [comment]
I think we're ready to release impyla

**Comment by laserson** [comment]
k, I'll do it later today

**Comment by wesm** [comment]
let's make one last pass then close this
