### ISSUE TITLE
can't build locally

### ISSUE THREAD

**Issue by esc** [cloudera/ibis#447]
`python setup.py build_ext -i` doesn't seem to do anything:

```
$ python setup.py build_ext -i
/data/home/vhaenel/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.4.0.dev' to '0.4.0.dev0'
running build_ext
```

**Comment by wesm** [comment]
There are no C/Cython extensions enabled in the build right now — we ran some UDF experiments late last year and developed the joint roadmap with Impala internals to enable zero-copy access to columnar data in shared memory.

**Comment by esc** [comment]
thanks
