### ISSUE TITLE
Don't install `requests_kerberos` by default

### ISSUE THREAD

**Issue by laserson** [cloudera/ibis#453]
Currently, ibis install will pull in `requests_kerberos` through the hdfs library.  Make it opt-in.  Thoughts?  @wesm

**Comment by laserson** [comment]
If we do this, make sure to update the docs that currently say that kerberos libs need to be installed.

**Comment by wesm** [comment]
Fine with me. We should raise an appropriate exception with ibis rather than letting it bubble up from elsewhere
