### ISSUE TITLE
hdfs_connect doesn't pass **kwds to hdfs.Client

### ISSUE THREAD

**Issue by nonsleepr** [cloudera/ibis#476]
Especially `root`, which should be set, otherwise `hdfs.resolve` will fail.

**Comment by wesm** [comment]
Thanks! If you would like to make PRs on Ibis can you complete a CLA http://docs.ibis-project.org/developer.html#contributor-license-agreements and send to cla AT cloudera.com (copy me: wes @ cloudera)

**Comment by wesm** [comment]
If the contributions are coming from CS, they will need to use the corporate CLA
