### ISSUE TITLE
docs.ibis-project.org contains exceptions in tutorial notebooks and inconsistent visibility of Tutorial in left-hand TOC

### ISSUE THREAD

**Issue by philz** [cloudera/ibis#511]
http://docs.ibis-project.org/generated-notebooks/4.html#uploading-downloading-data-from-hdfs contains a handful of exceptions; perhaps the notebook needs to be re-generated or re-converted?

Similarly, some pages (e.g., http://docs.ibis-project.org/configuration.html) are missing a Tutorial link in the left-hand navigation bar.

**Comment by wesm** [comment]
thanks, will fix

**Comment by wesm** [comment]
fixed
