### ISSUE TITLE
Make test data reusable on E2E tests

### ISSUE THREAD

**Issue by laserson** [cloudera/ibis#528]
Avoids having to reload on each test run.  UDFs should continue to be recompiled and reloaded each time, though. (Actually, perhaps we should load them into `tmp_db` instead)

**Comment by cpcloud** [comment]
The test data is reloaded on every CI run, and all tests are read only on tables that are used by other tests.

**Comment by wesm** [comment]
Yup, an artifact of running on the Cloudera Jenkins
