### ISSUE TITLE
Is there a way to run the cleanup tasks manually?

### ISSUE THREAD

**Issue by mariusvniekerk** [cloudera/ibis#533]
For a longer running process is there a way in ibis to close and ibis client and have the required cleanup jobs (dropping non-persisting tables, views, etc) run?

Needing to run 
```python
import gc
gc.collect()
```

feels rather scary.  

And even then i seem to have hiveserver2 sessions sticking around in the Impala daemon i connect to.

Something like a
```
client.close() 
```
would be very nice

**Comment by wesm** [comment]
Seems reasonable. I've been meaning to track all temporary database objects and have a cleanup API.
