### ISSUE TITLE
Add prospector run to jenkins job

### ISSUE THREAD

**Issue by laserson** [cloudera/ibis#616]
flake8/pylint violations will fail the jenkins build.

**Comment by laserson** [comment]
@wesm Here are the results from a prospector run with "medium" strictness.  Let me know if you'd like me to get cracking these.  It's also possible to disable the pylint messages at many levels of granularity.

https://gist.github.com/laserson/72b3f62464d4166be3d6

**Comment by wesm** [comment]
Oof, I would prefer to turn off the pylint and focus on flake8 violations mostly. It's helpful to occasionally look at, though.

**Comment by laserson** [comment]
Much more tractable.  Only two mccabe violations, but I can turn that off too.

```
$ prospector
Messages
========

dev/merge-pr.py
  Line: 263
    pyflakes: F821 / undefined name 'maybe_cherry_pick' (col 5)
  Line: 283
    pyflakes: F821 / undefined name 'latest_branch' (col 46)

ibis/impala/client.py
  Line: 1316
    mccabe: MC0001 / pandas_col_to_ibis_type is too complex (17)

ibis/impala/tests/test_pandas_interop.py
  Line: 138
    pyflakes: F841 / local variable 'inferred' is assigned to but never used (col 13)
  Line: 222
    pyflakes: F841 / local variable 'df' is assigned to but never used (col 9)

ibis/sql/compiler.py
  Line: 729
    mccabe: MC0001 / _adapt_expr is too complex (22)



Check Information
=================
         Started: 2015-09-03 18:33:30.808577
        Finished: 2015-09-03 18:33:37.452793
      Time Taken: 6.64 seconds
       Formatter: grouped
        Profiles: .landscape.yaml, no_doc_warnings, strictness_medium, strictness_high, strictness_veryhigh, no_member_warnings
      Strictness: from profile
  Libraries Used: 
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes
  Messages Found: 6
```

**Comment by laserson** [comment]
Are we maintaining `merge-pr.py`?  Or should I add it to an ignore list?

**Comment by wesm** [comment]
Leave that one, I like it. Thanks!

**Comment by wesm** [comment]
yeah ignore `merge-pr.py`

**Comment by laserson** [comment]
Only issue with leaving it on is that prospector returns with non-zero status if there are any messages output.

**Comment by wesm** [comment]
okay, let's disable it for now, and re-enable it after fixing those issues (which aren't that urgent)
