### ISSUE TITLE
Virtual Machine

### ISSUE THREAD

**Issue by nymoorland** [cloudera/ibis#639]
Currently no lean VM for pip-only per current docs. Many scientific and general Python users primarily use pip or their own setup.

**Comment by nymoorland** [comment]
I believe single node Hadoop VM has Impala. Could be made more explicit. I'll close this.

**Comment by wesm** [comment]
This is the second time you've opened and closed an issue like this. We have a lean VM linked to from the docs -- what else would you like us to do?

**Comment by nymoorland** [comment]
To be clear, add a line in the docs that indicate where and how to use the single node cluster VM. You reference something. Shall I update the docs to provide better detail and a link to this VM? It's fine that you have an option for "lean" VM but as already stated, you would be excluding a vast majority of Python user who don't use a second package manager and are not interested in installing it for various reasons. I am assuming that is part of the "audience for this product. Using it for builds is a different issue from meeting user needs. Sorry about the second issue, I was trying to edit/remove the first one. I learned that GIthub does not have this option. Thank you for re-opening and your reply. I do realize that you are adding sqllite and and other compute engine support.

**Comment by wesm** [comment]
Have you seen http://docs.ibis-project.org/getting-started.html#using-ibis-with-the-cloudera-quickstart-vm ?

**Comment by wesm** [comment]
Indeed SQLite support is dropping in 0.5 and Postgres will not be far behind

**Comment by nymoorland** [comment]
> Have you seen http://docs.ibis-project.org/getting-started.html#using-ibis-with-the-cloudera-quickstart-vm ? 

Yes, the reason the issue in the first place.

**Comment by wesm** [comment]
Okay, I will include a link to the VM file that is downloaded by following those instructions.

**Comment by nymoorland** [comment]
:+1:

**Comment by wesm** [comment]
I addressed this in my docs update branch

**Comment by djKooks** [comment]
@wesm Hello~This is just a question working on running below.
```
curl -s https://raw.githubusercontent.com/cloudera/ibis-notebooks/master/setup/bootstrap.sh | bash
```
What is quick start login ID/PW when running VM?

**Comment by wesm** [comment]
I'm not aware of the ID/password, see the command-line bootstrap script: https://github.com/cloudera/ibis-notebooks/blob/master/setup/setup-ibis-demo-vm.sh
