### ISSUE TITLE
pandas v0.17.0rc1

### ISSUE THREAD

**Issue by jreback** [cloudera/ibis#659]
we have some fairly significant changes and would like you to test and provide any feedback: https://github.com/pydata/pandas/releases/tag/v0.17.0rc1

thanks!

**Comment by wesm** [comment]
okay, let me have a look and get back to you about anything that will cause concern

**Comment by wesm** [comment]
This all looks good to me. Is there something you're particularly concerned about?

**Comment by jreback** [comment]
was looking for issues related to:

- using internal API's (which is the own projects issue when they, change although try to document event this, e.g. https://github.com/xray/xray/issues/571
- since deprecated a lot in the sort API, could cause downstream ``FutureWarnings`` (which of course in a new version would be fixed), but if don't want to overwhelm the end-user

thanks nothing to do then!
