### ISSUE TITLE
Postgres: implement window clause using SQLAlchemy

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#662]
Note: not all databases have window functions (e.g. SQLite does not)

**Comment by cpcloud** [comment]
I'm prototyping out supporting basic window functions in engines that don't support them with the standard `OVER ()` syntax.

The general approach I'm taking is to traverse the expression tree and rewrite `WindowOp`s. More specifically, when we reach a `WindowOp` expression, we rewrite it as a projection and replace the projection that the expression originally came from with the one that contains the window operation as well as replacing the window operation itself with a column selection from this new projection.

The initial implementation will support the following:
- [ ] All builtin aggregates
- [ ] `ORDER BY`
- [ ] `PARTITION BY`

Additional analytic functions such as `RANK()` and `ROW_NUMBER()` as well as support for moving windows may not make it into v1.

**Comment by cpcloud** [comment]
Closing, because we've implemented this for PostgreSQL. SQLite and other databases that don't have native support require a different approach. I have some thoughts on this, for which I will create another issue.
