### ISSUE TITLE
Performance issue when doing 1 record at a time - Perhaps use bulk bind techniques?

### ISSUE THREAD

**Issue by robert-lucente** [cloudera/ibis#691]
During Strata - 2015 - NYC, I had a hall way conversation w/ Wes McKinney. One of the things that we chit/chatted about was the performance issue of doing 1 record at a time. I suggested that he consider using "bulk bind" techniques which conventional databases have used to solve the problem. He liked the idea. I am sure that he was busier than normal and wanted to open an issue so that the idea does not get lost.

Below is a link to hopefully get him started in his research

https://docs.oracle.com/cd/B28359_01/appdev.111/b28370/tuning.htm

**Comment by wesm** [comment]
Thank you for the reference. The equivalent concept that is related to our plans with Ibis is the "vectorized UDF interface" as described on slide 28 in http://www.slideshare.net/wesm/ibis-scaling-python-analytics-on-hadoop-and-impala. Indeed, where interpreted languages are involved, operating on one batch of rows at a time versus 1 row at a time is essential for achieving good performance.
