### ISSUE TITLE
Add CHAR and VARCHAR Impala type handling

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#698]

**Comment by wesm** [comment]
@summerela this is fixed in upstream. I'm targeting 0.6 release sometime next week

**Comment by summerela** [comment]
Thank you, eagerly awaiting this fix!

**Comment by wesm** [comment]
I'm still trying up a few loose ends for the release. If you need the fix more urgently, you can install directly from git master

**Comment by summerela** [comment]
Works like a charm, thank you so much!

On Tue, Nov 3, 2015 at 10:53 AM, Wes McKinney <notifications@github.com>
wrote:

> I'm still trying up a few loose ends for the release. If you need the fix
> more urgently, you can install directly from git master
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudera/ibis/issues/698#issuecomment-153452635>.
>



-- 
Thanks,
Summer Rae
summerrae78@gmail.com
