### ISSUE TITLE
ibis_table.execute(limit=None) does not set limit to None

### ISSUE THREAD

**Issue by summerela** [cloudera/ibis#700]
Hi- 

The limit for table.execute() states that it is set by default to 'None'. However, the limit seems to be set at 10,000 by default, and remains set at 10,000 even when I expressly type 'limit=None' as a parameter. 

However if I expressly change the limit to a certain number, such as 200,000,000,000 it does successfully download all the rows of my ginormous table. 

For example, with verbose mode enabled: 

    # create ibis object from distinct vars table
    distinct_vars = con.table('global_variants', database='grch37') 
   
    SELECT * FROM grch37.`global_variants` LIMIT 0

    # limit table to just the columns we need to output to vcf
    distinct_df = distinct_vars[['chrom', 'pos', 'ref', 'alt']]

    # download table from ibis table connection object to local memory
    distinct_df = distinct_vars.execute(limit=None)

    SELECT *
    FROM grch37.`global_variants`
    LIMIT 10000

    # download table from ibis table connection object to local memory
     distinct_df = distinct_vars.execute(limit=30000)

    SELECT *
    FROM grch37.`global_variants`
    LIMIT 30000

**Comment by wesm** [comment]
Thanks -- I shall investigate

**Comment by wesm** [comment]
This is no wfixed in upstream
