### ISSUE TITLE
Pegged version dep to something that seems old

### ISSUE THREAD

**Issue by mariusvniekerk** [cloudera/ibis#723]
Version dependency pegged in meta.yaml

- psutil ==0.6.1

The latest version of psutil as reported by conda search is  3.2.2

Should we try and move this up?

**Comment by wesm** [comment]
Unfortunately all of the Python in Impala requires psutil 0.6.1. I am going to remove the requirement altogether as it is not needed in Ibis at the moment. Marked for 0.6

**Comment by mariusvniekerk** [comment]
Curious about the  issues that it could cause? .   I've been using ibis and impyla for months now with a more recent version without any apparent problems on legacy python with some master build of thrift

**Comment by wesm** [comment]
I actually mean the Impala system scripts itself (cloudera/impala). It's laziness on my part as I should be using a virtualenv or conda environment for all my interactions with Impala (which depends on a number of older libraries because they have been supporting Python 2.4 until recently).

**Comment by mariusvniekerk** [comment]
Ah right. That explains it.
