### ISSUE TITLE
SQL Syntax Error when performing parse_url

### ISSUE THREAD

**Issue by napjon** [cloudera/ibis#745]
From [parse_url](http://docs.ibis-project.org/generated/ibis.expr.api.StringValue.parse_url.html) example,

```Python
arg = 'https://www.youtube.com/watch?v=kEuEcWfewf8&t=10'
expr = ibis.expr.api.StringValue.parse_url(arg, 'QUERY', 'v')
print(ibis.impala.compile(expr))
```

Result in 

```SQL
SELECT
  parse_url('https://www.youtube.com/watch?v=kEuEcWfewf8&t=10', 'QUERY', Literal[string]
    v) AS `tmp`
```

which will gives Syntax Error because `LITERAL[string]` in the query.

**Comment by wesm** [comment]
Thanks, I will fix. Note that `ibis.expr.api.StringValue.parse_url` is not an intended use. The intended way to use this function is by:

```python
expr = ibis.literal(arg)
arg.parse_url(...)
```

**Comment by wesm** [comment]
This is fixed in master

**Comment by napjon** [comment]
Got it. thank you for the quick fix!
