### ISSUE TITLE
Re-enable concurrent Jenkins builds for different Python versions

### ISSUE THREAD

**Issue by laserson** [cloudera/ibis#764]
For some reason, running concurrent builds on nightly for the different Python version is causing problems like

```
E           HiveServer2Error: AnalysisException: Could not resolve path: '__ibis_tmp_d1bf505bb264496d847cc450fa2ec8a0.731a576b2ad640fc80f643de6c269297'
```

sporadically in different tests.  Seems to go away if I run the tests sequentially.

**Comment by cpcloud** [comment]
We're running circleci tests against all versions of python that we support.
