### ISSUE TITLE
ImpalaClient.create_table doesn't always respect `format` kwarg

### ISSUE THREAD

**Issue by dlovell** [cloudera/ibis#771]
ImpalaClient.create_table accepts `format` kwarg but [hard codes](https://github.com/cloudera/ibis/blob/master/ibis/impala/client.py#L847) `ddl.NoFormat` when `schema` arg is used in place of `obj` (`TableExpr` or `DataFrame`)

**Comment by dlovell** [comment]
if `HOST` is set properly in the code below
``` python
import ibis
 
tablename = 'should_be_parquet'
schema = ibis.schema([('id', 'int32'), ('name', 'string')])
HOST = <HOST>
 
client = ibis.impala.connect(HOST)
db = client.database()
db.create_table(tablename, schema=schema, format='PARQUET')
stats = db[tablename].stats()
print(stats.irow(0).Format)
```
it prints
> TEXT

**Comment by tsdlovell** [comment]
Since `CreateTableWithSchema`'s `table_format` arg is hardcoded anyways, maybe best temporary solution is to define `ParquetFormat` in ddl.py and hardcode the `table_format` arg to that.  At least that way its in line with the default `format` arg of 'parquet'

``` python
class ParquetFormat(object):

    def to_ddl(self):
        return '\nSTORED AS PARQUET'
```

**Comment by wesm** [comment]
Thanks! Slating for 0.6.1

**Comment by halfaleague** [comment]
This makes the format respect what is given (or do something like this ...)
https://github.com/cloudera/ibis/pull/784
