### ISSUE TITLE
partition insert fails when partition key is a string

### ISSUE THREAD

**Issue by statmatt** [cloudera/ibis#774]
For partition keys that are string, table.insert() does not appropriately wrap the static partition value of the string in quotes, in particular where the static partition value is contained within a Python variable. The documentation example uses integer partition values and thus does not address this case.

Example:

tblSchema = ibis.schema(
    [
        ('a': int32),
        ('b': 'string')
    ]
)
db.create_table('test_table', schema=tblSchema, partition=['b'])
tbl = db.table('test_table')
the_partition='the_partition_value'
tbl.insert(some_table_reference, partition={'b': the_partition})

--> impala.error.HiveServer2Error: AnalysisException: Non-constant expressions are not supported as static partition-key values in 'b=the_partition_value'.

**Comment by wesm** [comment]
Thanks, will fix soon

**Comment by statmatt** [comment]
Thanks Wes -

also found this morning that in interactive mode, table.info() does not
print a newline after the final line of the output, so you get the line
cursor on the same line as the last row of the table description.


Thanks!


Matt

On Wednesday, January 6, 2016, Wes McKinney <notifications@github.com>
wrote:
> Thanks, will fix soon
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/G2jFhI71Jda-iMFvdGSSJLIAfBGHBVR5Fdo36kwiXG5P9cw1ALp9sxoUIpqqnY_NUPYLsUMSSH90TRnfcPPfd804pVr6gj0P1z0-pBb0NtPZzeqvGWi1OtJNG0sCBbFy17OiLQCL7jPUm_nesq-ltnCJw156Sg=s0-d-e1-ft#https://github.com/notifications/beacon/AE4pkT_KQewwNKeuvbYlN1cKp3aRAqYuks5pXTi5gaJpZM4G_Km0.gif
>

-- 
Matt Anthony
statmatt@gmail.com
"Achieving the impossible is merely stringing together a series of the
possible." - GOLF54 teaching mantra
"The best way to predict the future is to create it." - Peter Drucker
