### ISSUE TITLE
TableExpr.info formatting

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#776]
Mentioned in #774 

> also found this morning that in interactive mode, table.info() does not
> print a newline after the final line of the output, so you get the line
> cursor on the same line as the last row of the table description.

**Comment by wesm** [comment]
@statmatt could you clarify? I am seeing

```
In [8]: t.info()
Table rows: 7300

Column           Type       Non-null #
------           ----       ----------
id               int32      7300      
bool_col         boolean    7300      
tinyint_col      int8       7300      
smallint_col     int16      7300      
int_col          int32      7300      
bigint_col       int64      7300      
float_col        float      7300      
double_col       double     7300      
date_string_col  string     7300      
string_col       string     7300      
timestamp_col    timestamp  7300      
year             int32      7300      
month            int32      7300      
In [9]: 
```

**Comment by statmatt** [comment]
Yes ... And then when doing that in interactive mode, the command line is
presented at the end of that last line (this is raw command line, not
ipython).

I can send you a snippet tmrw if you need one.


Matt

On Wednesday, January 6, 2016, Wes McKinney <notifications@github.com>
wrote:

> @statmatt <https://github.com/statmatt> could you clarify? I am seeing
>
> In [8]: t.info()
> Table rows: 7300
>
> Column           Type       Non-null #
> ------           ----       ----------
> id               int32      7300
> bool_col         boolean    7300
> tinyint_col      int8       7300
> smallint_col     int16      7300
> int_col          int32      7300
> bigint_col       int64      7300
> float_col        float      7300
> double_col       double     7300
> date_string_col  string     7300
> string_col       string     7300
> timestamp_col    timestamp  7300
> year             int32      7300
> month            int32      7300
> In [9]:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudera/ibis/issues/776#issuecomment-169540972>.
>


-- 
Matt Anthony
statmatt@gmail.com
"Achieving the impossible is merely stringing together a series of the
possible." - GOLF54 teaching mantra
"The best way to predict the future is to create it." - Peter Drucker

**Comment by wesm** [comment]
Got it, fixing now. Here's what I have now:

```
>>> import ibis
>>> hdfs = ibis.hdfs_connect(port=5070)
>>> c = ibis.impala.connect(hdfs_client=hdfs)
>>> db = c.database('functional')
>>> t = db.alltypes
>>> t.info()
Table rows: 7300

Column           Type       Non-null #
------           ----       ----------
id               int32      7300      
bool_col         boolean    7300      
tinyint_col      int8       7300      
smallint_col     int16      7300      
int_col          int32      7300      
bigint_col       int64      7300      
float_col        float      7300      
double_col       double     7300      
date_string_col  string     7300      
string_col       string     7300      
timestamp_col    timestamp  7300      
year             int32      7300      
month            int32      7300     
```

**Comment by statmatt** [comment]
Thanks Wes!

On Wednesday, January 6, 2016, Wes McKinney <notifications@github.com>
wrote:

> Got it, fixing now. Here's what I have now:
>
> >>> import ibis
> >>> hdfs = ibis.hdfs_connect(port=5070)
> >>> c = ibis.impala.connect(hdfs_client=hdfs)
> >>> db = c.database('functional')
> >>> t = db.alltypes
> >>> t.info()
> Table rows: 7300
>
> Column           Type       Non-null #
> ------           ----       ----------
> id               int32      7300
> bool_col         boolean    7300
> tinyint_col      int8       7300
> smallint_col     int16      7300
> int_col          int32      7300
> bigint_col       int64      7300
> float_col        float      7300
> double_col       double     7300
> date_string_col  string     7300
> string_col       string     7300
> timestamp_col    timestamp  7300
> year             int32      7300
> month            int32      7300
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudera/ibis/issues/776#issuecomment-169541465>.
>


-- 
Matt Anthony
statmatt@gmail.com
"Achieving the impossible is merely stringing together a series of the
possible." - GOLF54 teaching mantra
"The best way to predict the future is to create it." - Peter Drucker
