### ISSUE TITLE
Using http for webhdfs not possible when kerberos is enabled 

### ISSUE THREAD

**Issue by mwullink** [cloudera/ibis#778]
The hdfs_connect function has no option to choose http or https protocol when connecting to webhdfs.
We are running CDH 5.5 with kerberos but without ssl enabled for webhdfs.

Could you maybe add an option to signal the use of http when using kerberos?

code snippet.

the hdfs_connect function code in ibis/ibis/__init__.py always uses https when auth_mechanism in ['GSSAPI', 'LDAP']

example:

def hdfs_connect(host='localhost', port=50070, protocol='webhdfs',
                 auth_mechanism='NOSASL', verify=True, use_https=True, **kwds):

if auth_mechanism in ['GSSAPI', 'LDAP']:
        try:
            import requests_kerberos
        except ImportError:
            raise IbisError(
                "Unable to import requests-kerberos, which is required for "
                "Kerberos HDFS support. Install it by executing `pip install "
                "requests-kerberos` or `pip install hdfs[kerberos]`.")
        from hdfs.ext.kerberos import KerberosClient
        if use_https:
            url = 'https://{0}:{1}'.format(host, port) # use SSL
        else:
            url = 'http://{0}:{1}'.format(host, port) # no SSL
        kwds.setdefault('mutual_auth', 'OPTIONAL')
        hdfs_client = KerberosClient(url, **kwds)
    else:
        from hdfs.client import InsecureClient
        url = 'http://{0}:{1}'.format(host, port)
        hdfs_client = InsecureClient(url, **kwds)

**Comment by wesm** [comment]
Sure thing. I'll take a look when I can

**Comment by wesm** [comment]
Just did this in trunk; will be a part of Ibis 0.7. Let me know if you run into any issues
