### ISSUE TITLE
execute() only pulls maximum of 10,000 rows when no parameter is supplied

### ISSUE THREAD

**Issue by statmatt** [cloudera/ibis#786]
>>> cnt_by_destIP.info()
Table rows: 251613

Column             Type    Non-null #
------             ----    ----------
sensor_id          int32   251613    
dest_ip            string  251613    
unique_flow_count  int64   251613    
source_bytes       int64   251613    
dest_bytes         int64   251613

>>> cnt_by_destIP.execute().shape
(10000, 5)

>>> cnt_by_destIP.execute(500000).shape
(251613, 5)

The documentation on this function is incorrect, specifying that supplying no parameter will export the entire table, where clearly this is not the case. Please correct the code so that the condition specified in the documentation is how the execute() method operates.

**Comment by wesm** [comment]
hi Matt,

Here's what the documentation says currently:

```
        Parameters
        ----------
        limit : integer or None, default 'default'
          Pass an integer to effect a specific row limit. limit=None means "no
          limit". The default is whatever is in ibis.options.
```

So to get the whole table, you can pass `expr.execute(limit=None)`. Patches welcome on this and any other documentation issues -- let me know if you found wrong information someplace else
