### ISSUE TITLE
Left Outer Join execution is incorrect

### ISSUE THREAD

**Issue by statmatt** [cloudera/ibis#790]
In the example below, the expectation is that the left-join of table A should have at least one row per row of table A, and in fact the results does not. As far as I can tell, this is due to predicate pushdown on the filtering keys to outside of the table statements, and this results in incorrect output. Extracting these predicates is improper in outer join, and subsequently the same failure can be seen on full outer join as well as left outer join.

In a case like this, the statement should be compiled to an "as-is" interpretation of the query inputs, as Ibis can't necessarily predict the result of the predicate pushdown. 

Left join is explicit in that the output table has cardinality at or greater than the left table, and the results here clearly do not, meaning that the software package missed a significant checkpoint in QA.

>>> tbl_a = db.table('a')
>>> tbl_a_filter = tbl_a.filter(
...    [
...        tbl_a.year == 2016,
...        tbl_a.month == 2,
...        tbl_a.day == 29
...    ]
...)
>>> tbl_a_filter.info()
Table rows: 684291734
...

>>> tbl_b = db.table('b')
>>> tbl_b_filter = tbl_b.filter(
...    [
...        tbl_b.year == 2016,
...        tbl_b.month == 2,
...        tbl_b.day == 29
...    ]
...)
>>> tbl_b_info.info()
Table rows: 62536
...

>>> joined = ibis.join(
...    tbl_a,
...    tbl_b,
...    [
...        <set of join keys ...>
...    ],
...    how='left'
...)[
    tbl_a,
    tbl_b
]
>>> joined_flows.info()
Table rows: 64092
...

**Comment by wesm** [comment]
Sorry about this -- I believe this may be the same bug as #781. Let me see if I can find some time this weekend or early next week to fix this -- appreciate the detailed reproduction as it will make fixing much easier.

**Comment by statmatt** [comment]
It does look to be the same issue.

Thanks for looking into it.

**Comment by wesm** [comment]
Oops, didn't mean to close this.

**Comment by wesm** [comment]
Take a look at the master branch and let me know if you original use case works, it should now!

**Comment by statmatt** [comment]
Thanks, will try to take a look today.
