### ISSUE TITLE
Ibis choose wrong schema

### ISSUE THREAD

**Issue by napjon** [cloudera/ibis#807]
Hi,

I'm running Ibis 0.7.0 with Python 3.5. Below is the code to reproduce the issue,

```Python
x = ibis.table(ibis.schema([('a','string'),
                        ('b','string'),
                        ('n_x', 'int64')]))

y = ibis.table(ibis.schema([('a','string'),
                        ('b','string'),
                        ('n_y', 'int64')]))

joined =  x.join(y,[x.a == y.a, x.b == y.b])[x.a,x.b,x.n_x,y.n_y]

joined_avg = (joined
              .mutate(ratio = joined.n_x / joined.n_y)
              .aggregate(avg_ratio = lambda x: x.ratio.mean(), by='a'))

joined_avg[joined_avg.avg_ratio.between(1,3)]
```

This generates,

```Python
KeyError: "'avg_ratio' is not a field"
```

Or many filtering operation on `avg_ratio` will generates same issue I guess.

debugging this, the TabExpr used to detect the field is `joined.schema()` instead of `joined_avg.schema()`

**Comment by wesm** [comment]
Thanks. This is the result of an analysis error -- I have slated it for the next bugfix release (probably the end of April unless someone patches this sooner -- I am unavailable much of this month)

**Comment by napjon** [comment]
@cpcloud : Amazing work, thank you!
