### ISSUE TITLE
Union All/With Syntax Error

### ISSUE THREAD

**Issue by marshall245** [cloudera/ibis#821]
Using union with complex TableExpr can yield syntax such as :

.....
UNION ALL
WITH t1 as (
......

this then yields a syntax error/

**Comment by wesm** [comment]
Interesting, I will have a look

**Comment by cpcloud** [comment]
@marshall245 Can you give an example ibis expression that results in this error?

**Comment by cpcloud** [comment]
@marshall245 I was able to find one in the test suite and reproduce the problem, but feel free to post one if you have it at the ready.

**Comment by marshall245** [comment]
Hey guys,

Sorry for the slow turn around. I have attached an example notebook. The
example is a bit contrived. We came by the first honestly while unioning a
query to the data in a partition for the purposes of rewriting the
partition in an updated form. Thanks for having a look.

**Comment by wesm** [comment]
The attachment didn't come through because of github -- feel free to e-mail us the details offline if you prefer

**Comment by wesm** [comment]
It looks like this might be an issue of putting parentheses around the unioned query

http://www.cloudera.com/documentation/archive/impala/2-x/2-1-x/topics/impala_with.html

I'll try to come up with a test case to reproduce.

**Comment by cpcloud** [comment]
I think there's a deeper problem here. It's possible to generate a query that contains multiple with statements, e.g., unioning two joins that have a subquery.

**Comment by wesm** [comment]
I think that may be OK -- obviously it would be better to do subquery factoring through each of the unioned subqueries (so if there is a common subquery between two union components, it gets factored out to a top level WITH clause), but we might be able to work around this for now by adding parenthesis

**Comment by wesm** [comment]
see #666 (cryptic description, but i think this is a related issue)

**Comment by cpcloud** [comment]
I have a fix to add the parens. For future reference, at what stage of the compilation pipeline should the factoring out happen? After a few attempts in the last couple of hours I think a sane approach might be to track the common subqueries in the expression, ripping them out of the `left` and `right` fields. Then during compilation of `ImpalaUnion`, build the `WITH`s and the minimized `left` and `right`. @wesm Does that seem reasonable?

**Comment by wesm** [comment]
@cpcloud that sounds like what I did in #837, take a look and let me know if that wasn't what you were thinking.

I think it may be possible to extract subqueries "above" the union (that's what's referenced in #666), but that will be some more work. This at least gives us working code without a ton of effort

**Comment by cpcloud** [comment]
This can be closed. Will add more comments after looking at #837 more closely.
