### ISSUE TITLE
Filtering a TableExpr using one of its columns

### ISSUE THREAD

**Issue by tdhopper** [cloudera/ibis#827]
I was trying to filter a `TableExpr` created by a `group_by` operation on one of it's own columns. I get a `KeyError: "'col' is not a field"` exception. 

I reproduced it here: https://gist.github.com/tdhopper/f20db628c2e496828bf6afb2c7c2eebd.

If I drop into the stack with pdb, I see that the `if name not in table_expr.schema():` line, I see that `name` corresponds to the named column in the `group_by` table, while `table_expr` corresponds to the original table (which doesn't have that column).

**Comment by tdhopper** [comment]
Possibly the same as #807

**Comment by cpcloud** [comment]
I'll add a test for this in #822

**Comment by cpcloud** [comment]
Actually, this is the same bug so the test should be sufficient to cover this case too.

**Comment by cpcloud** [comment]
This can be closed now
