### ISSUE TITLE
locale.nl_langinfo doesn't exist on windows  

### ISSUE THREAD

**Issue by pyite1** [cloudera/ibis#844]
```
C:\Users\xxxxx\AppData\Local\Continuum\Anaconda2\lib\site-packages\ibis\sql\postgres\compiler.py in <module>()
    160     '%U': 'WW',  # 1-based week of year
    161     # 'W': ?,  # meh
--> 162     '%c': locale.nl_langinfo(locale.D_T_FMT),  # locale date and time
    163     '%x': locale.nl_langinfo(locale.D_FMT),  # locale date
    164     '%X': locale.nl_langinfo(locale.T_FMT)  # locale time

AttributeError: 'module' object has no attribute 'nl_langinfo'
```

perhaps leveraging locale.getdefaultlocale() could be a workaround?

**Comment by francescog** [comment]
I stumbled on the same issue. This happens becaunse nl_langinfo is not available on Windows (see [To](http://stackoverflow.com/q/13401587/159684) ). Just be able to at least "import ibis" I commented out those lines and substituted them with a hard-coded format.

**Comment by cpcloud** [comment]
Thanks for the report! Will get this fixed ASAP.
