### ISSUE TITLE
Null Type can't be converted to Array

### ISSUE THREAD

**Issue by napjon** [cloudera/ibis#849]
I have ibis version 'v0.8.1' and I ran the following,

```Python
In [1]: import ibis

In [2]: t = ibis.table(ibis.schema([('a','string')]))

In [3]: t.mutate(b=ibis.null()).columns
Out[3]: ['a', 'b']

In [4]: t.mutate(b=ibis.null())['b']


AttributeError: module 'ibis.expr.types' has no attribute 'NullArray'
```

I can't select NullArray by column name. Is this expected?

**Comment by wesm** [comment]
This is definitely a bug. The resolved type of a null scalar may be implementation dependent, so what you can reasonably do with null types may be limited:

```
> select typeof(e) from (select NULL AS e) t0;
Query: select typeof(e) from (select NULL AS e) t0
+--------------+
| typeof(null) |
+--------------+
| BOOLEAN      |
+--------------+
Fetched 1 row(s) in 0.01s
```

```
postgres=# select pg_typeof(e) from (select NULL AS e) t0;
 pg_typeof 
-----------
 unknown
(1 row)
```

**Comment by napjon** [comment]
thanks for working on this!

Just want to make sure. One of the use cases that I currently working on is converting tables to common schema so I can union them. Suppose I have two tables,

```Python
t = ibis.table(ibis.schema([('a','string'),
                                         ('b','string')]))

t2 =  ibis.table(ibis.schema([('a','string')]))
```
t1 has column `b` of StringArray, and t2 doesn't have it. So I create `b` column with null type.  

Of course I get error where I tried to union since it required the same schema. I suppose we can't do it like in pandas, like null type converted to string type but null value? My solution right now is just creating literal empty string  as new column.

**Comment by cpcloud** [comment]
@napjon You can cast null values to any type, so that the union would have the same schema.

I'll be sure to add a test for this to make sure it's possible.

For your convenience, you don't actually need to pass in `ibis.schema()` you can just pass in list of tuples, which saves you a few characters :)

**Comment by cpcloud** [comment]
@napjon Added tests in the PR. To do what you're talking about using your `t1` and `t2`, here's how you would do it:

```
In [1]: import ibis

In [2]: t1 = ibis.table(ibis.schema([('a','string'),('b','string')]))

In [3]: t2 = ibis.table(ibis.schema([('a','string')]))

In [4]: mutated = t2.mutate(b=ibis.NA.cast('string'))

In [5]: union = t1.union(mutated)
```

**Comment by napjon** [comment]
Got it, thanks @cpcloud!
