### ISSUE TITLE
Default HDFS client port is not consistent

### ISSUE THREAD

**Issue by cpcloud** [cloudera/ibis#867]
It appears that the HDFS client port defaults to 50070 in `hdfs_connect`, but the environment variable defaults to 5070. When connecting to the impala docker image, the default port was 5070. I think we should change this to 5070 everywhere.

```sh
$ ag '500?70'
docs/source/impala.rst
24:   hdfs = ibis.hdfs_connect(port=5070)

ibis/impala/tests/common.py
51:        # 5070 is default for impala dev env
52:        self.webhdfs_port = int(os.environ.get('IBIS_TEST_WEBHDFS_PORT', 5070))

ibis/impala/tests/test_kudu_support.py
56:                                               50070))

ibis/__init__.py
38:def hdfs_connect(host='localhost', port=50070, protocol='webhdfs',
47:    port : int, NameNode's WebHDFS port (default 50070)
```

**Comment by cpcloud** [comment]
Unless I'm missing something here and this is intentional.

**Comment by wesm** [comment]
The Impala dev environment uses 5070 for the webhdfs port. My understanding in normal HDFS deployments is that the default port is 50070. I'm not sure of the exact reason for this, though.

**Comment by cpcloud** [comment]
Ok, cool. Good to know.
