### ISSUE TITLE
BUG: Incorrectly decreasing connection_pool_size

### ISSUE THREAD

**Issue by maxmzkr** [cloudera/ibis#870]
Impala cursors decrease the connection_pool_size even if they weren't taken from the connetion pool.

``` python
    def __del__(self):
        self._close_cursor()
        with self.con.lock:
            self.con.connection_pool_size -= 1
```

An example of a cursor not coming from the connection pool

``` python
class ImpalaConnection(object):
    def ping(self):
        self._new_cursor()
```

This causes all ImpalaClients to start with a connection_pool_size of -1 which allows the connection pool to increase 1 higher than it's supposed to.

**Comment by wesm** [comment]
thanks for catching this, how did you run into this problem?

**Comment by maxmzkr** [comment]
I was tracking down https://github.com/cloudera/ibis/issues/871 and ran into this first

**Comment by cpcloud** [comment]
I have a fix for this. I'll put it up when I'm back in NYC.
