### ISSUE TITLE
'ImpalaDatabase' object has no attribute '_repr_json_'

### ISSUE THREAD

**Issue by tdhopper** [cloudera/ibis#876]
In a Jupyter notebook, if I call the `database` method of an `ImpalaConnection` without assigning the output to a variable, I get 

```
DESCRIBE prd.`_repr_json_`
Exception caused by DESCRIBE prd.`_repr_json_`: Traceback (most recent call last):
  File "/Users/tdhopper/miniconda/envs/env/lib/python3.5/site-packages/ibis/client.py", line 377, in __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'ImpalaDatabase' object has no attribute '_repr_json_'
```

This is a Jupyter-specific thing, but I don't understand exactly what's going on here. Maybe it can be ignored.

This is in Ibis 0.8.1.

**Comment by wesm** [comment]
Interesting. Probably should fix this

**Comment by cpcloud** [comment]
What's the function of the `special_attrs` variable in `__getattr__`? Why not just let Python's attribute lookup mechanism take its course? Is there something I'm missing?

**Comment by cpcloud** [comment]
Ah, nevermind.

**Comment by cpcloud** [comment]
I can't reproduce this. @tdhopper Please reopen if you're still seeing this.

![no-repro](https://cloud.githubusercontent.com/assets/417981/23191010/643bfe12-f869-11e6-97b1-ede7cdc45e9e.png)
