### ISSUE TITLE
AttributeError: 'module' object has no attribute 'nl_langinfo'

### ISSUE THREAD

**Issue by ZuluagaSD** [cloudera/ibis#881]
I'm getting the AttributeError: 'module' object has no attribute 'nl_langinfo' when I try to import ibis.

I'm currently using a Windows 7 box with a python distribution installed using Anaconda.

![image](https://cloud.githubusercontent.com/assets/1851696/18640894/cb6e1afe-7e5f-11e6-9523-7ae9aa65f072.png)

**Comment by ZuluagaSD** [comment]
Looks like I "fixed" the error bellow when I do:

`import locale`
`locale.setlocale(locale.LC_ALL, 'english')`

But now I'm getting a similar error:

![image](https://cloud.githubusercontent.com/assets/1851696/18641291/9c2ea7ac-7e61-11e6-86c6-18fcf3a4d20d.png)

**Comment by cpcloud** [comment]
Are you on the latest version of ibis? This should've been fixed by #845

**Comment by cpcloud** [comment]
From the traceback it looks like you're not on the latest version. Please update and reopen if you still experience this error. Thanks for reporting!

**Comment by ZuluagaSD** [comment]
You are right, I just updated from the GitHub repo and it's working now. Thanks!
