### ISSUE TITLE
'DoubleArray' object does not support indexing

### ISSUE THREAD

**Issue by ragesz** [cloudera/ibis#883]
I just want to convert ibis table into pandas dataframe. I don't know how to do this basic step. I've tried creating lists from columns with no success. Then I tried to get a single value from a cell:
`table['col_name'][0]`

And I get this error:

> 'DoubleArray' object does not support indexing

How can I do these basic steps in ibis: indexing, converting?

Thank you!

**Comment by wesm** [comment]
Run `.execute()` on the expression to get the in-memory pandas result

**Comment by ragesz** [comment]
Thank you! It works perfectly!
Actually I started using impyla when I was blocked by this issue. But now I had some time to turn back to ibis. And as I see both has the same runtime performance (at least in my project).
