### ISSUE TITLE
Error with projection involving aggregate functions

### ISSUE THREAD

**Issue by tdhopper** [cloudera/ibis#897]
I've got this code:
```
import ibis
t1 = ibis.table(name='t1', schema=[('y', 'int32'), ('z', 'int32')])
print(ibis.impala.compile(t1.projection([t1.y.std()])))
```
which returns
```
SELECT stddev(`y`) OVER () AS `std`
FROM t1
```

If I try to run it on Impala, I get `impala.error.HiveServer2Error: AnalysisException: Aggregate function 'stddev(`y`)' not supported with OVER clause.`

However, it's no problem to just run `t1.y.std().execute()`because that doesn't generate the `OVER ()`.

Why is the `OVER ()` added in the projection? It doesn't need to be. This may be related to #407.

**Comment by wesm** [comment]
When you use reductions in a projection, ibis thinks you're trying to do a window function. For example:

```python
In [5]: t[t, (t.y - t.y.mean()).name('y_demean')]
   ...: 
Out[5]: 
ref_0
UnboundTable[table]
  name: t1
  schema:
    y : int32
    z : int32

Selection[table]
  table:
    Table: ref_0
  selections:
    Table: ref_0
    y_demean = Subtract[array(double)]
      y = Column[array(int32)] 'y' from table ref_0
      mean = WindowOp[double]
        mean = Mean[double]
          y = Column[array(int32)] 'y' from table ref_0
          None
        <ibis.expr.window.Window object at 0x7f652be3b8d0>
```

this works though:

```
t.aggregate(t.y.mean())
```

**Comment by cpcloud** [comment]
The behavior here is correct, though the word "projection" doesn't necessarily imply (other than by definition) that it has no effect on the number of rows in a relation (derived or otherwise), only the number of columns.
