### ISSUE TITLE
Can I access in demo vm?

### ISSUE THREAD

**Issue by djKooks** [cloudera/ibis#943]
Hello,
I'm currently following up running demo, but couldn't access on VM like below.
![2017-02-20 9 35 13](https://cloud.githubusercontent.com/assets/1720209/23125369/b72c898a-f7b4-11e6-8281-a2b395850ad6.png)

Do I need an account for working on demo?

**Comment by cpcloud** [comment]
This information is available on the cloudera website: https://www.cloudera.com/downloads/quickstart_vms/5-8.html

Please reopen the issue if you're still experiencing problems.

**Comment by djKooks** [comment]
@cpcloud Thanks! I'll keep look on it.
