### ISSUE TITLE
AttributeError: module 'ibis.impala' has no attribute 'connect'

### ISSUE THREAD

**Issue by sheldon66** [cloudera/ibis#978]
I want to create a impala connect by following the doc. This is my code:

`import ibis
con = ibis.impala.connect(host='XXX.XXX.XXX.XXX', port=21050,
                          auth_mechanism='PLAIN',user='XXXXX', password='XXXXX')`

But running it will raise an error:
**`AttributeError: module 'ibis.impala' has no attribute 'connect'`**
Please help!

**Comment by sheldon66** [comment]
I figure it out. The location of function connect has been changed.
Now the correct code is:
`import ibis 
con = ibis.impala.api.connect(host='XXX.XXX.XXX.XXX', port=21050, auth_mechanism='PLAIN',user='XXXXX', password='XXXXX')`

**Comment by wesm** [comment]
Hm, I have

```
In [1]: import ibis

In [2]: ibis.impala.connect
Out[2]: <function ibis.impala.api.connect>
```

could you let us know more information about how you ran into this?

**Comment by sheldon66** [comment]
Now the problem happened again.And this time even with api added, the error still there.
```
localhost:~ sheldon$ pip3 install ibis-framework
Collecting ibis-framework
Requirement already satisfied: toolz in /usr/local/lib/python3.5/site-packages (from ibis-framework)
Requirement already satisfied: numpy>=1.7.0 in /usr/local/lib/python3.5/site-packages (from ibis-framework)
Requirement already satisfied: six in /usr/local/lib/python3.5/site-packages (from ibis-framework)
Requirement already satisfied: pandas>=0.12.0 in /usr/local/lib/python3.5/site-packages (from ibis-framework)
Requirement already satisfied: python-dateutil>=2 in /usr/local/lib/python3.5/site-packages (from pandas>=0.12.0->ibis-framework)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.5/site-packages (from pandas>=0.12.0->ibis-framework)
Installing collected packages: ibis-framework
Successfully installed ibis-framework-0.10.0
localhost:~ sheldon$ python3
Python 3.5.2 (default, Oct 11 2016, 04:59:56)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibis
>>> ibis.impala.connect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ibis.impala' has no attribute 'connect'
>>> ibis.impala.api.connect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ibis.impala' has no attribute 'api'
>>>
```
I am using macbook pro. Could you help me find out where the problem is?

**Comment by cpcloud** [comment]
@sheldon66 Do you have a file named `impala.py` in the directory you're running this from? If so, you need to name that file something else, and remove `impala.pyc` if it exists.

As per [the Python documentation](https://docs.python.org/3/tutorial/modules.html#the-module-search-path), here's likely why you're getting this error when accessing `ibis.impala`:

1. `import ibis`: Python finds `ibis` in the installation-dependent directory
1. `ibis.impala`: Python searches *the current directory* before search the installation dependent directory and finds your file called `impala.py` and imports it automatically.
1. Since your `impala.py` has no attribute `connect` or `api`, you get the error you show.

**Comment by sheldon66** [comment]
There isn't a file named `impala.py` in my current directory. And the impala module imported correct.
```
localhost:~ sheldon$ python3
Python 3.5.2 (default, Oct 11 2016, 04:59:56)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibis
>>> print(ibis.impala.__file__)
/usr/local/lib/python3.5/site-packages/ibis/impala/__init__.py
>>> print(ibis.impala.api.__file__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ibis.impala' has no attribute 'api'
>>>
```

**Comment by cpcloud** [comment]
@sheldon66 I'm able to reproduce this now! My apologies for misunderstanding. Fix on the way :)

**Comment by cpcloud** [comment]
Looks like we have a circular import.

**Comment by cpcloud** [comment]
@sheldon66 Have you install `impyla`?

**Comment by sheldon66** [comment]
Amazing! After I installed `impyla`, the problem solved. I still don't understand why it happened.

**Comment by cpcloud** [comment]
It's because impyla installs a top level module called `impala` (unrelated to `ibis.impala`). This was not being imported because it wasn't installed.

**Comment by sheldon66** [comment]
So that means before I install `Ibis`, I should install `impyla` first? If so , why don't add it to `Ibis`'s dependency?

**Comment by cpcloud** [comment]
It is a dependency, but only if you want to use the impala backend which isn't a requirement to use the library.

**Comment by cpcloud** [comment]
Hm, it looks like our docs are not up to date.

**Comment by cpcloud** [comment]
@wesm How do we update the docs?

**Comment by sheldon66** [comment]
@cpcloud Thank you so much for helping me out :)

**Comment by wesm** [comment]
If we update the sphinx docs here I can deploy them

**Comment by sc0303** [comment]
I come across the same question, however no matter install or uninstall impyla, I still get the same AttributeError: module 'ibis.impala' has no attribute 'connect' result, could you pls help, the version of ibis is the newest

**Comment by sc0303** [comment]
After re-install ibis-framwork, the problem solved, thx

**Comment by ddonetskov** [comment]
I came across the same issue when trying to use ibis for Impala. What has helped is to install the framework in the proper way (see below, it's also in the [documentation](http://docs.ibis-project.org/getting-started.html), the 'Impala Quickstart' section). I suggest outlining in the documentation that there are several options how to install ibis.

`pip install ibis-framework[impala]`

**Comment by sambit19** [comment]
I had the same issue and fixed it by uninstalling and reinstalling using the command below:

```
conda uninstall ibis-framework
conda install ibis-framework -c conda-forge
```
It works now.
